Disable anti-amplification limit by address validation token
lucas-clemente/quic-go pull request #3326
Opened 2022-01-28 12:06 UTC by birneee

2022-01-28 12:58 UTC, marten-seemann reviewed
This looks pretty good already. Can you add a unit test in the ackhandler package?

2022-01-28 12:58 UTC, marten-seemann commented on internal/ackhandler/ackhandler.go
> +// clientAddressValidated indicates weather the address was validated beforehand by an address validation token.
```suggestion
// clientAddressValidated indicates whether the address was validated beforehand by an address validation token.
```

2022-01-28 12:58 UTC, marten-seemann commented on internal/ackhandler/ackhandler.go
> +	clientAddressValidated bool,
Nit: move this after the `rttStats`.

2022-01-28 12:58 UTC, marten-seemann commented on internal/ackhandler/sent_packet_handler.go
> +	clientAddressValidated bool,
Here too.

2022-01-28 12:58 UTC, marten-seemann commented on session.go
> +	clientAddressValidated bool,
Nit: move this after `enable0RTT`.

2022-01-28 12:58 UTC, marten-seemann commented on internal/ackhandler/sent_packet_handler.go
> +// clientAddressValidated has no effect for a client.
```suggestion
// If the address was validated, the amplification limit doesn't apply. It has no effect for a client.
```

2022-02-01 01:03 UTC, birneee commented
@marten-seemann please check again

2022-02-06 15:31 UTC, marten-seemann requested changes

2022-02-06 15:31 UTC, marten-seemann commented on internal/ackhandler/sent_packet_handler.go
> +// clientAddressValidated indicates weather the address was validated beforehand by an address validation token.
```suggestion
// clientAddressValidated indicates whether the address was validated beforehand by an address validation token.
```

2022-02-06 15:31 UTC, marten-seemann commented on internal/ackhandler/sent_packet_handler_test.go
> +			Expect(handler.peerAddressValidated).To(Equal(true))
It would be better to test the expected behavior than to make assertion on implementation details.

2022-02-20 13:07 UTC, marten-seemann commented
@birneee Are you still working on this? Would love to get this merged!

2022-02-20 18:09 UTC, birneee commented
@marten-seemann i just worked on it :)

2022-02-21 12:57 UTC, marten-seemann approved these changes

2022-02-21 13:05 UTC, marten-seemann requested changes
So, I messed up this review. Sorry for that!

I don't think it's correct to use the result of `AcceptToken`. Consider the following scenario: A server only wants to enable Retries when it's under load. Therefore, it will return `true` from the `AcceptToken` callback when it is not under load. However, that doesn't mean that we should trust the address and send an unlimited amount of data there.

2022-02-21 15:06 UTC, birneee commented
@marten-seemann you are right, because the AcceptToken can be configured. The defaultAcceptToken function however checks the validity. So we could either use a function similar to defaultAcceptToken by calling it directly or add a new config ValidateToken, where by default AcceptToken = ValidateToken. But I am not sure if ValidateToken should be configurable.

2022-05-13 22:10 UTC, birneee commented
@marten-seemann please check
I think, configuring token validity is another issue.

2022-08-13 15:04 UTC, marten-seemann commented
@birneee We just completely rewrote the Retry API in #3501 (see #3494 for design considerations). As the token validation logic now lives inside quic-go, this should make it possible to disable the anti-amplification limit when we successfully validated a token.

Do you want to rebase and modify your PR to take advantage of this? Fixing #3319 would be a super valuable contribution for everyone who actually wants to take full advantage of 0-RTT.

2022-08-16 15:53 UTC, birneee commented
@marten-seemann it is rebased now

2022-08-20 15:02 UTC, marten-seemann approved these changes
This looks very clean! Thank you @birneee!

2022-08-20 15:02 UTC, merged