fix: datagram support detection
lucas-clemente/quic-go pull request #3511
Opened 2022-08-19 23:41 UTC by KevinZonda

- treat zero MaxDatagramFrameSize as unsupported.
- avoid send corresponding transport parameters when support is disabled
- report error when calling Send/ReceiveMessage and support is disabled

see https://github.com/lucas-clemente/quic-go/issues/3505

2022-08-20 02:52 UTC, TNQOYxNU commented
This replace #3507

2022-08-20 08:19 UTC, marten-seemann reviewed
It seems like the `datagramQueue` should be initialized when we receive the peer's transport parameters, not on setup, right?

2022-08-20 13:34 UTC, TNQOYxNU commented
> It seems like the `datagramQueue` should be initialized when we receive the peer's transport parameters, not on setup, right?

I'm neither familiar with code base nor with standard, so this PR doesn't address this problem, only add a nil check to avoid go panic.
To support "unidirectional datagram", it need to be initiated somewhere, initiate it on demand after peer's transport parameter is the best option.
Another option is always initiate it on setup regardless configuration, straightforward but may have some overhead.
We'd better also disable `Send/ReceiveMessage` on demand, improve doc, even redesign ConnectionState API to avoid confusion--it's two independent unidirectional channel.

2022-08-20 14:19 UTC, TNQOYxNU commented
Initiate `datagramQueue` after transport parameter (`connection.applyTransportParameters()`) not works, seems `newPacketPacker` need `datagramQueue` before transport parameter available?
Always initiate it in `connection.preSetup()` passed all test cases.

2022-08-20 14:54 UTC, marten-seemann commented
> Always initiate it in connection.preSetup() passed all test cases.

Sounds good to me. Then we can send datagrams, even if we don't support receiving datagrams. Can you update the PR?

2022-08-22 08:47 UTC, marten-seemann requested changes

2022-08-22 08:47 UTC, marten-seemann commented on connection.go
> +	if s.datagramQueue == nil || !s.supportsDatagrams() {
I think you can remove the `s.datagramQueue == nil` check. You initialize the `datagramQueue` in all cases.

2022-08-22 09:48 UTC, marten-seemann approved these changes

2022-08-22 10:02 UTC, merged